# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'topupbanking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for topupbanking

  target 'topupbankingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'topupbankingUITests' do
    # Pods for testing
  end
  
pod "DropDown"
  
end
